name: Test and verify core infrastructure

on: [pull_request]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: set up terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_PROVIDER_ARN }}
          role-session-name: CoreInfraPullRequestWorkflow
          aws-region: us-east-1
      - name: lint terraform config
        run: terraform -chdir=infra fmt -check
      - name: set up terraform environment
        run: terraform -chdir=infra init
      - name: validate terraform config
        run: terraform -chdir=infra validate -no-color
      - name: plan terraform infrastructure
        run: |
          terraform -chdir=infra plan -no-color -input=false
