name: Test and verify core infrastructure

on: [pull_request]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: set up terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_GH_ACTION_ROLE_ARN }}
          role-session-name: CoreInfraPullRequestWorkflow
          aws-region: us-east-1
      - name: lint terraform config
        run: terraform fmt -check
      - name: set up terraform environment
        run: terraform init
      - name: validate terraform config
        run: terraform validate -no-color
      - name: plan terraform infrastructure
        run: |
          terraform plan -no-color -input=false
